name: Deploy to EKS
on:
  repository_dispatch:
    types:
      - deploy_to_eks  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Fetch Image Tag from Repo A
      run: |
        echo "Fetched Image Tag: ${{ github.event.client_payload.image_tag }}"  # This gets the image tag sent from Repo A

    - name: Update Deployment File with New Image Tag
      run: |
        sed -i 's|image: .*|image: 058264137181.dkr.ecr.eu-west-1.amazonaws.com/github-testing:${{ github.event.client_payload.image_tag }}|' deployment.yaml

    - name: Deployment completed successfully
      run: |
        echo "Deployment completed successfully"
