name: Workflow02
on:
  repository_dispatch:
    types:
      - trigger-workflow02

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2  
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Fetch Image Tag from Repo A
      run: |
        if [[ -z "${{ github.event.client_payload.image_tag }}" ]]; then
          echo "Image tag is not provided"
          exit 1
        else
          echo "Fetched Image Tag: ${{ github.event.client_payload.image_tag }}"
        fi

    - name: Debugging
      run: |
        echo "Checking the contents of deployment.yaml"
        cat test/deployment.yaml

    - name: Update Deployment File with New Image Tag
      run: |
        echo "Updating the image tag in deployment.yaml"
        if [[ -f test/deployment.yaml ]]; then
          sed -i'' -e 's|image: .*|image: 058264137181.dkr.ecr.eu-west-1.amazonaws.com/github-testing:${{ github.event.client_payload.image_tag }}|' test/deployment.yaml
        else
          echo "deployment.yaml file not found!"
          exit 1
        fi

    - name: after update
      run: |
        echo "Checking the contents of deployment.yaml after update"
        cat test/deployment.yaml
